apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  namespace: jans
data:
  CN_CONFIG_ADAPTER: "kubernetes"
  CN_SECRET_ADAPTER: "kubernetes"
  CN_SECRET_KUBERNETES_NAMESPACE: "jans"
  CN_CONFIG_KUBERNETES_NAMESPACE: "jans"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: config-load
  namespace: jans
spec:
  template:
    metadata:
      labels:
        app: config-load
      namespace: jans
    spec:
      restartPolicy: Never
      volumes:
        - name: config-generate-params
          configMap:
            name: config-generate-params
      containers:
        - name: config-load
          image: docker.io/janssenproject/configuration-manager:5.0.0_dev
          volumeMounts:
            - mountPath: /app/db/generate.json
              name: config-generate-params
              subPath: generate.json
          envFrom:
          - configMapRef:
              name: config-cm
          args: ["load"]
