apiVersion: v1
kind: ConfigMap
metadata:
  name: jans-fido2-cm
  namespace: jans
data:
  CN_CONFIG_ADAPTER: "kubernetes"
  CN_SECRET_ADAPTER: "kubernetes"
  DOMAIN: "demoexample.jans.io"
  CN_LDAP_URL: "opendj:1636"
  CN_SECRET_KUBERNETES_NAMESPACE: "jans"
  CN_CONFIG_KUBERNETES_NAMESPACE: "jans"

---

apiVersion: v1
kind: Service
metadata:
  name: jans-fido2
  labels:
    app: jans-fido2
  namespace: jans
spec:
  ports:
  - port: 8080
    name: jans-fido2
  selector:
    app: jans-fido2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jans-fido2
  labels:
    app: jans-fido2
  namespace: jans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jans-fido2
  template:
    metadata:
      labels:
        app: jans-fido2
      namespace: jans
    spec:
      containers:
      - name: jans-fido2
        image: docker.io/janssenproject/fido2:1.0.0_dev
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: jans-fido2-cm
        # livenessProbe:
        #   exec:
        #     command: ["python3", "/app/scripts/healthcheck.py"]
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   exec:
        #     command: ["python3", "/app/scripts/healthcheck.py"]
        #   initialDelaySeconds: 25
        #   periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - demoexample.jans.io
